from __future__ import annotations

import math
import os
from pathlib import Path
import shutil
import subprocess
import wave

from PIL import Image

from app.core.assets3d.license import check_license
from app.core.assets3d.manifest import AssetRecord, load_manifest, upsert_asset, update_last_used
from app.core.assets3d.pruner import prune_assets
from app.core.assets3d.scorer import score_audio, score_character, score_environment
from app.core.paths import get_assets_root
from app.core.visuals.anime_3d.blender_installer import ensure_blender_path
from app.core.visuals.anime_3d.storage import ensure_storage_budget, compute_required_bytes


ASSET_CAP_BYTES = 115 * 1024**3
MIN_COUNTS = {"character": 2, "environment": 3, "sfx": 1, "music": 1}


def _asset_size(path: Path) -> int:
    if path.is_dir():
        return sum(p.stat().st_size for p in path.rglob("*") if p.is_file())
    if path.exists():
        return path.stat().st_size
    return 0


def _total_assets_size(root: Path) -> int:
    return sum(p.stat().st_size for p in root.rglob("*") if p.is_file())


def _write_license(asset_id: str) -> Path:
    license_dir = get_assets_root() / "licenses"
    license_dir.mkdir(parents=True, exist_ok=True)
    proof_path = license_dir / f"{asset_id}.txt"
    proof_path.write_text("CC0 - generated by MoneyOS", encoding="utf-8")
    return proof_path


def _generate_audio_asset(path: Path, duration_s: float = 1.5, sample_rate: int = 44100) -> None:
    total_frames = int(duration_s * sample_rate)
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(sample_rate)
        for i in range(total_frames):
            t = i / sample_rate
            sample = int(12000 * math.sin(2 * math.pi * 220 * t))
            handle.writeframes(sample.to_bytes(2, byteorder="little", signed=True))


def _generate_vfx_asset(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img = Image.new("RGBA", (256, 256), (0, 0, 0, 0))
    for x in range(256):
        for y in range(256):
            alpha = int(255 * (1 - abs(x - 128) / 128) * (1 - abs(y - 128) / 128))
            img.putpixel((x, y), (255, 180, 50, max(alpha, 0)))
    img.save(path)


def _run_blender_asset_script(script_path: Path, args: list[str]) -> None:
    blender_path = ensure_blender_path()
    command = [
        str(blender_path),
        "--background",
        "--factory-startup",
        "--python",
        str(script_path),
        "--",
        *args,
    ]
    result = subprocess.run(command, check=False, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Blender asset generation failed: {result.stderr[-1000:]}")


def _ensure_blender_assets() -> list[tuple[str, Path, str]]:
    assets_root = get_assets_root()
    script_path = Path(__file__).parents[2] / "visuals" / "anime_3d" / "blender" / "generate_assets.py"
    output_dir = assets_root / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    required = [
        ("hero", output_dir / "hero.blend", "character"),
        ("enemy", output_dir / "enemy.blend", "character"),
        ("city", output_dir / "city.blend", "environment"),
        ("street", output_dir / "street.blend", "environment"),
        ("studio", output_dir / "studio.blend", "environment"),
    ]
    missing = [item for item in required if not item[1].exists()]
    if missing:
        extraction_overhead = int(os.getenv("MONEYOS_EXTRACTION_OVERHEAD_BYTES", str(300 * 1024**2)))
        ensure_storage_budget([assets_root], compute_required_bytes(extraction_overhead=extraction_overhead), "extract")
        if os.getenv("MONEYOS_SELFTEST") == "1":
            for _, path, _ in missing:
                path.write_bytes(b"MoneyOS selftest asset")
        else:
            args = ["--output-dir", str(output_dir)]
            _run_blender_asset_script(script_path, args)
    return required


def _register_assets(job_id: str | None, items: list[tuple[str, Path, str]]) -> None:
    manifest = load_manifest()
    for asset_id, path, asset_type in items:
        license_proof = _write_license(asset_id)
        license_check = check_license("CC0", str(license_proof))
        if not license_check.allowed:
            raise RuntimeError(f"license rejected for {asset_id}: {license_check.reason}")
        size = _asset_size(path)
        if asset_type == "character":
            score = score_character(True, True, 1)
        elif asset_type == "environment":
            score = score_environment(40, 40)
        else:
            score = score_audio(True, True)
        threshold = {"character": 80, "environment": 75, "sfx": 70, "music": 70, "vfx": 70}.get(asset_type, 70)
        if score.score < threshold:
            raise RuntimeError(f"Asset {asset_id} below quality threshold {threshold}")
        record = AssetRecord(
            asset_id=asset_id,
            asset_type=asset_type,
            source_url="local://generated",
            license_name=license_check.name or "CC0",
            license_url=license_check.url,
            license_proof_path=str(license_proof),
            size_bytes=size,
            score_total=score.score,
            score_breakdown=score.breakdown,
            pinned=False,
            last_used_at=None,
            in_use_by_job_ids=[job_id] if job_id else [],
            local_paths=[str(path)],
        )
        upsert_asset(record)
        update_last_used(asset_id, job_id=job_id)
    _ = manifest


def ensure_minimum_assets(job_id: str | None = None) -> None:
    assets_root = get_assets_root()
    estimated_download = int(os.getenv("MONEYOS_ESTIMATED_DOWNLOAD_BYTES", str(200 * 1024**2)))
    extraction_overhead = int(os.getenv("MONEYOS_EXTRACTION_OVERHEAD_BYTES", str(200 * 1024**2)))
    required_bytes = compute_required_bytes(
        estimated_download_size=estimated_download,
        extraction_overhead=extraction_overhead,
    )
    try:
        ensure_storage_budget([assets_root], required_bytes, "download")
    except RuntimeError:
        prune_assets(min_free_bytes=int(os.getenv("MONEYOS_MIN_FREE_BYTES", str(15 * 1024**3))))
        ensure_storage_budget([assets_root], required_bytes, "download")
    prune_assets(min_free_bytes=int(os.getenv("MONEYOS_MIN_FREE_BYTES", str(15 * 1024**3))))
    total_size = _total_assets_size(assets_root)
    if total_size >= ASSET_CAP_BYTES:
        print("[ASSETS] download cap reached (115GB); proceeding with best-scoring assets", flush=True)
    items = _ensure_blender_assets() if total_size < ASSET_CAP_BYTES else []
    if items:
        _register_assets(job_id, items)

    sfx_path = assets_root / "sfx" / "impact.wav"
    music_path = assets_root / "music" / "bed.wav"
    vfx_path = assets_root / "vfx" / "burst.png"
    for path in [sfx_path, music_path]:
        if not path.exists() and total_size < ASSET_CAP_BYTES:
            ensure_storage_budget([assets_root], required_bytes, "download")
            _generate_audio_asset(path)
    if not vfx_path.exists():
        _generate_vfx_asset(vfx_path)

    _register_assets(
        job_id,
        [
            ("impact", sfx_path, "sfx"),
            ("bed", music_path, "music"),
            ("burst", vfx_path, "vfx"),
        ],
    )

    manifest = load_manifest()
    for asset_type, count in MIN_COUNTS.items():
        items = [record for record in manifest.get("assets", {}).values() if record.get("type") == asset_type]
        if len(items) < count:
            raise RuntimeError("Minimum asset set not met; cannot proceed.")

    current_size = _total_assets_size(assets_root)
    if current_size >= ASSET_CAP_BYTES:
        print("[ASSETS] download cap reached (115GB); proceeding with best-scoring assets", flush=True)

    generated_dir = assets_root / "generated"
    characters_dir = assets_root / "characters"
    env_dir = assets_root / "envs"
    characters_dir.mkdir(parents=True, exist_ok=True)
    env_dir.mkdir(parents=True, exist_ok=True)
    normalize_overhead = int(os.getenv("MONEYOS_NORMALIZE_OVERHEAD_BYTES", str(100 * 1024**2)))
    ensure_storage_budget([assets_root], compute_required_bytes(extraction_overhead=normalize_overhead), "normalize")
    for name in ["hero", "enemy"]:
        src = generated_dir / f"{name}.blend"
        dest = characters_dir / f"{name}.blend"
        if src.exists() and not dest.exists():
            shutil.copy2(src, dest)
    for name in ["city", "street", "studio"]:
        src = generated_dir / f"{name}.blend"
        dest = env_dir / f"{name}.blend"
        if src.exists() and not dest.exists():
            shutil.copy2(src, dest)
